//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class authenticationRequest {
    
    private string passwordField;
    
    private string usernameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(personLink))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(identifierUpdateEntry))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(identifierUpdateEvent))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(address))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(user))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(religion))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(race))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(phoneType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(personIdentifier))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(nationality))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(nameType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(language))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(gender))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ethnicGroup))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(addressType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(person))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(linkSource))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(reviewRecordPair))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public abstract partial class baseObject {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class address : baseObject {
    
    private string address1Field;
    
    private string cityField;
    
    private string countryField;
    
    private string postalCodeField;
    
    private string provinceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string address1 {
        get {
            return this.address1Field;
        }
        set {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string postalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class user : baseObject {
    
    private bool accountExpiredField;
    
    private bool accountLockedField;
    
    private address addressField;
    
    private bool credentialsExpiredField;
    
    private string emailField;
    
    private bool enabledField;
    
    private string firstNameField;
    
    private long idField;
    
    private bool idFieldSpecified;
    
    private string lastNameField;
    
    private string passwordField;
    
    private string passwordHintField;
    
    private string phoneNumberField;
    
    private string usernameField;
    
    private string websiteField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool accountExpired {
        get {
            return this.accountExpiredField;
        }
        set {
            this.accountExpiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool accountLocked {
        get {
            return this.accountLockedField;
        }
        set {
            this.accountLockedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public address address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool credentialsExpired {
        get {
            return this.credentialsExpiredField;
        }
        set {
            this.credentialsExpiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool enabled {
        get {
            return this.enabledField;
        }
        set {
            this.enabledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool idSpecified {
        get {
            return this.idFieldSpecified;
        }
        set {
            this.idFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string passwordHint {
        get {
            return this.passwordHintField;
        }
        set {
            this.passwordHintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string username {
        get {
            return this.usernameField;
        }
        set {
            this.usernameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string website {
        get {
            return this.websiteField;
        }
        set {
            this.websiteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class religion : baseObject {
    
    private int religionCdField;
    
    private bool religionCdFieldSpecified;
    
    private string religionCodeField;
    
    private string religionDescriptionField;
    
    private string religionNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int religionCd {
        get {
            return this.religionCdField;
        }
        set {
            this.religionCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool religionCdSpecified {
        get {
            return this.religionCdFieldSpecified;
        }
        set {
            this.religionCdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string religionCode {
        get {
            return this.religionCodeField;
        }
        set {
            this.religionCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string religionDescription {
        get {
            return this.religionDescriptionField;
        }
        set {
            this.religionDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string religionName {
        get {
            return this.religionNameField;
        }
        set {
            this.religionNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class phoneType : baseObject {
    
    private int phoneTypeCdField;
    
    private bool phoneTypeCdFieldSpecified;
    
    private string phoneTypeCodeField;
    
    private string phoneTypeDescriptionField;
    
    private string phoneTypeNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int phoneTypeCd {
        get {
            return this.phoneTypeCdField;
        }
        set {
            this.phoneTypeCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool phoneTypeCdSpecified {
        get {
            return this.phoneTypeCdFieldSpecified;
        }
        set {
            this.phoneTypeCdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneTypeCode {
        get {
            return this.phoneTypeCodeField;
        }
        set {
            this.phoneTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneTypeDescription {
        get {
            return this.phoneTypeDescriptionField;
        }
        set {
            this.phoneTypeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneTypeName {
        get {
            return this.phoneTypeNameField;
        }
        set {
            this.phoneTypeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class nationality : baseObject {
    
    private int nationalityCdField;
    
    private bool nationalityCdFieldSpecified;
    
    private string nationalityCodeField;
    
    private string nationalityDescriptionField;
    
    private string nationalityNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int nationalityCd {
        get {
            return this.nationalityCdField;
        }
        set {
            this.nationalityCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nationalityCdSpecified {
        get {
            return this.nationalityCdFieldSpecified;
        }
        set {
            this.nationalityCdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nationalityCode {
        get {
            return this.nationalityCodeField;
        }
        set {
            this.nationalityCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nationalityDescription {
        get {
            return this.nationalityDescriptionField;
        }
        set {
            this.nationalityDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nationalityName {
        get {
            return this.nationalityNameField;
        }
        set {
            this.nationalityNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class nameType : baseObject {
    
    private int nameTypeCdField;
    
    private bool nameTypeCdFieldSpecified;
    
    private string nameTypeCodeField;
    
    private string nameTypeDescriptionField;
    
    private string nameTypeNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int nameTypeCd {
        get {
            return this.nameTypeCdField;
        }
        set {
            this.nameTypeCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool nameTypeCdSpecified {
        get {
            return this.nameTypeCdFieldSpecified;
        }
        set {
            this.nameTypeCdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nameTypeCode {
        get {
            return this.nameTypeCodeField;
        }
        set {
            this.nameTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nameTypeDescription {
        get {
            return this.nameTypeDescriptionField;
        }
        set {
            this.nameTypeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string nameTypeName {
        get {
            return this.nameTypeNameField;
        }
        set {
            this.nameTypeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class language : baseObject {
    
    private int languageCdField;
    
    private bool languageCdFieldSpecified;
    
    private string languageCodeField;
    
    private string languageDescriptionField;
    
    private string languageNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int languageCd {
        get {
            return this.languageCdField;
        }
        set {
            this.languageCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool languageCdSpecified {
        get {
            return this.languageCdFieldSpecified;
        }
        set {
            this.languageCdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string languageCode {
        get {
            return this.languageCodeField;
        }
        set {
            this.languageCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string languageDescription {
        get {
            return this.languageDescriptionField;
        }
        set {
            this.languageDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string languageName {
        get {
            return this.languageNameField;
        }
        set {
            this.languageNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ethnicGroup : baseObject {
    
    private int ethnicGroupCdField;
    
    private bool ethnicGroupCdFieldSpecified;
    
    private string ethnicGroupCodeField;
    
    private string ethnicGroupDescriptionField;
    
    private string ethnicGroupNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int ethnicGroupCd {
        get {
            return this.ethnicGroupCdField;
        }
        set {
            this.ethnicGroupCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ethnicGroupCdSpecified {
        get {
            return this.ethnicGroupCdFieldSpecified;
        }
        set {
            this.ethnicGroupCdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ethnicGroupCode {
        get {
            return this.ethnicGroupCodeField;
        }
        set {
            this.ethnicGroupCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ethnicGroupDescription {
        get {
            return this.ethnicGroupDescriptionField;
        }
        set {
            this.ethnicGroupDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ethnicGroupName {
        get {
            return this.ethnicGroupNameField;
        }
        set {
            this.ethnicGroupNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class addressType : baseObject {
    
    private int addressTypeCdField;
    
    private bool addressTypeCdFieldSpecified;
    
    private string addressTypeCodeField;
    
    private string addressTypeDescriptionField;
    
    private string addressTypeNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int addressTypeCd {
        get {
            return this.addressTypeCdField;
        }
        set {
            this.addressTypeCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool addressTypeCdSpecified {
        get {
            return this.addressTypeCdFieldSpecified;
        }
        set {
            this.addressTypeCdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string addressTypeCode {
        get {
            return this.addressTypeCodeField;
        }
        set {
            this.addressTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string addressTypeDescription {
        get {
            return this.addressTypeDescriptionField;
        }
        set {
            this.addressTypeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string addressTypeName {
        get {
            return this.addressTypeNameField;
        }
        set {
            this.addressTypeNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class linkSource : baseObject {
    
    private int linkSourceIdField;
    
    private bool linkSourceIdFieldSpecified;
    
    private string sourceDescriptionField;
    
    private string sourceNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int linkSourceId {
        get {
            return this.linkSourceIdField;
        }
        set {
            this.linkSourceIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool linkSourceIdSpecified {
        get {
            return this.linkSourceIdFieldSpecified;
        }
        set {
            this.linkSourceIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceDescription {
        get {
            return this.sourceDescriptionField;
        }
        set {
            this.sourceDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sourceName {
        get {
            return this.sourceNameField;
        }
        set {
            this.sourceNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class gender : baseObject {
    
    private int genderCdField;
    
    private bool genderCdFieldSpecified;
    
    private string genderCodeField;
    
    private string genderDescriptionField;
    
    private string genderNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int genderCd {
        get {
            return this.genderCdField;
        }
        set {
            this.genderCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool genderCdSpecified {
        get {
            return this.genderCdFieldSpecified;
        }
        set {
            this.genderCdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string genderCode {
        get {
            return this.genderCodeField;
        }
        set {
            this.genderCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string genderDescription {
        get {
            return this.genderDescriptionField;
        }
        set {
            this.genderDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string genderName {
        get {
            return this.genderNameField;
        }
        set {
            this.genderNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class identifierDomain {
    
    private System.DateTime dateCreatedField;
    
    private bool dateCreatedFieldSpecified;
    
    private string identifierDomainDescriptionField;
    
    [Key]
    private int identifierDomainIdField;
    
    private bool identifierDomainIdFieldSpecified;
    
    private string identifierDomainNameField;
    
    private string namespaceIdentifierField;
    
    private string universalIdentifierField;
    
    private string universalIdentifierTypeCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateCreatedSpecified {
        get {
            return this.dateCreatedFieldSpecified;
        }
        set {
            this.dateCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string identifierDomainDescription {
        get {
            return this.identifierDomainDescriptionField;
        }
        set {
            this.identifierDomainDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int identifierDomainId {
        get {
            return this.identifierDomainIdField;
        }
        set {
            this.identifierDomainIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool identifierDomainIdSpecified {
        get {
            return this.identifierDomainIdFieldSpecified;
        }
        set {
            this.identifierDomainIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string identifierDomainName {
        get {
            return this.identifierDomainNameField;
        }
        set {
            this.identifierDomainNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string namespaceIdentifier {
        get {
            return this.namespaceIdentifierField;
        }
        set {
            this.namespaceIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string universalIdentifier {
        get {
            return this.universalIdentifierField;
        }
        set {
            this.universalIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string universalIdentifierTypeCode {
        get {
            return this.universalIdentifierTypeCodeField;
        }
        set {
            this.universalIdentifierTypeCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class identifierDomainAttribute {
    
    private string attributeNameField;
    
    private string attributeValueField;
    
    private int identifierDomainAttributeIdField;
    
    private bool identifierDomainAttributeIdFieldSpecified;
    
    private int identifierDomainIdField;
    
    private bool identifierDomainIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string attributeName {
        get {
            return this.attributeNameField;
        }
        set {
            this.attributeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string attributeValue {
        get {
            return this.attributeValueField;
        }
        set {
            this.attributeValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int identifierDomainAttributeId {
        get {
            return this.identifierDomainAttributeIdField;
        }
        set {
            this.identifierDomainAttributeIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool identifierDomainAttributeIdSpecified {
        get {
            return this.identifierDomainAttributeIdFieldSpecified;
        }
        set {
            this.identifierDomainAttributeIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int identifierDomainId {
        get {
            return this.identifierDomainIdField;
        }
        set {
            this.identifierDomainIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool identifierDomainIdSpecified {
        get {
            return this.identifierDomainIdFieldSpecified;
        }
        set {
            this.identifierDomainIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class identifierDomainAttributeRequest {
    
    private string attributeNameField;
    
    private string attributeValueField;
    
    private identifierDomain identifierDomainField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string attributeName {
        get {
            return this.attributeNameField;
        }
        set {
            this.attributeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string attributeValue {
        get {
            return this.attributeValueField;
        }
        set {
            this.attributeValueField = value;
        }
    }
    
    /// <remarks/>
    public identifierDomain identifierDomain {
        get {
            return this.identifierDomainField;
        }
        set {
            this.identifierDomainField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class identifierUpdateEntry : baseObject {
    
    private string identifierField;
    
    private identifierDomain identifierDomainField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    public identifierDomain identifierDomain {
        get {
            return this.identifierDomainField;
        }
        set {
            this.identifierDomainField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class identifierUpdateEvent : baseObject {
    
    private System.DateTime dateCreatedField;
    
    private bool dateCreatedFieldSpecified;
    
    private long identifierUpdateEventIdField;
    
    private bool identifierUpdateEventIdFieldSpecified;
    
    private identifierUpdateEntry[] postUpdateIdentifiersField;
    
    private identifierUpdateEntry[] preUpdateIdentifiersField;
    
    private string sourceField;
    
    private string transitionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateCreatedSpecified {
        get {
            return this.dateCreatedFieldSpecified;
        }
        set {
            this.dateCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long identifierUpdateEventId {
        get {
            return this.identifierUpdateEventIdField;
        }
        set {
            this.identifierUpdateEventIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool identifierUpdateEventIdSpecified {
        get {
            return this.identifierUpdateEventIdFieldSpecified;
        }
        set {
            this.identifierUpdateEventIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("postUpdateIdentifier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public identifierUpdateEntry[] postUpdateIdentifiers {
        get {
            return this.postUpdateIdentifiersField;
        }
        set {
            this.postUpdateIdentifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("preUpdateIdentifier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public identifierUpdateEntry[] preUpdateIdentifiers {
        get {
            return this.preUpdateIdentifiersField;
        }
        set {
            this.preUpdateIdentifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string source {
        get {
            return this.sourceField;
        }
        set {
            this.sourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string transition {
        get {
            return this.transitionField;
        }
        set {
            this.transitionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class mergePersonsRequest {
    
    private personIdentifier retiredIdentifierField;
    
    private personIdentifier survivingIdentiferField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public personIdentifier retiredIdentifier {
        get {
            return this.retiredIdentifierField;
        }
        set {
            this.retiredIdentifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public personIdentifier survivingIdentifer {
        get {
            return this.survivingIdentiferField;
        }
        set {
            this.survivingIdentiferField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class personIdentifier : baseObject {
    
    private System.DateTime dateCreatedField;
    
    private bool dateCreatedFieldSpecified;
    
    private System.DateTime dateVoidedField;
    
    private bool dateVoidedFieldSpecified;
    
    private string identifierField;
    
    private identifierDomain identifierDomainField;
    
    private int personIdentifierIdField;
    
    private bool personIdentifierIdFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateCreatedSpecified {
        get {
            return this.dateCreatedFieldSpecified;
        }
        set {
            this.dateCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateVoided {
        get {
            return this.dateVoidedField;
        }
        set {
            this.dateVoidedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateVoidedSpecified {
        get {
            return this.dateVoidedFieldSpecified;
        }
        set {
            this.dateVoidedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string identifier {
        get {
            return this.identifierField;
        }
        set {
            this.identifierField = value;
        }
    }
    
    /// <remarks/>
    public identifierDomain identifierDomain {
        get {
            return this.identifierDomainField;
        }
        set {
            this.identifierDomainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int personIdentifierId {
        get {
            return this.personIdentifierIdField;
        }
        set {
            this.personIdentifierIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool personIdentifierIdSpecified {
        get {
            return this.personIdentifierIdFieldSpecified;
        }
        set {
            this.personIdentifierIdFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class person : baseObject {
    
    private string accountField;
    
    private identifierDomain accountIdentifierDomainField;
    
    private string address1Field;
    
    private string address2Field;
    
    private addressType addressTypeField;
    
    private int birthOrderField;
    
    private bool birthOrderFieldSpecified;
    
    private string birthPlaceField;
    
    private string cellField;
    
    private string cellIdField;
    
    private string cityField;
    
    private string countryField;
    
    private string countryCodeField;
    
    private string custom1Field;
    
    private string custom10Field;
    
    private string custom11Field;
    
    private string custom12Field;
    
    private string custom13Field;
    
    private string custom14Field;
    
    private string custom15Field;
    
    private string custom16Field;
    
    private string custom17Field;
    
    private string custom18Field;
    
    private string custom19Field;
    
    private string custom2Field;
    
    private string custom20Field;
    
    private string custom3Field;
    
    private string custom4Field;
    
    private string custom5Field;
    
    private string custom6Field;
    
    private string custom7Field;
    
    private string custom8Field;
    
    private string custom9Field;
    
    private System.DateTime dateChangedField;
    
    private bool dateChangedFieldSpecified;
    
    private System.DateTime dateCreatedField;
    
    private bool dateCreatedFieldSpecified;
    
    private System.DateTime dateOfBirthField;
    
    private bool dateOfBirthFieldSpecified;
    
    private System.DateTime dateVoidedField;
    
    private bool dateVoidedFieldSpecified;
    
    private string deathIndField;
    
    private System.DateTime deathTimeField;
    
    private bool deathTimeFieldSpecified;
    
    private string degreeField;
    
    private string districtField;
    
    private string districtIdField;
    
    private string emailField;
    
    private ethnicGroup ethnicGroupField;
    
    private string familyNameField;
    
    private string familyName2Field;
    
    private string fatherNameField;
    
    private gender genderField;
    
    private string givenNameField;
    
    private string groupNumberField;
    
    private language languageField;
    
    private string maritalStatusCodeField;
    
    private string middleNameField;
    
    private string motherNameField;
    
    private string mothersMaidenNameField;
    
    private string multipleBirthIndField;
    
    private nameType nameTypeField;
    
    private nationality nationalityField;
    
    private int personIdField;
    
    private bool personIdFieldSpecified;
    
    private personIdentifier[] personIdentifiersField;
    
    private string phoneAreaCodeField;
    
    private string phoneCountryCodeField;
    
    private string phoneExtField;
    
    private string phoneNumberField;
    
    private phoneType phoneTypeField;
    
    private string postalCodeField;
    
    private string prefixField;
    
    private string provinceField;
    
    private race raceField;
    
    private religion religionField;
    
    private string sectorField;
    
    private string sectorIdField;
    
    private string ssnField;
    
    private string stateField;
    
    private string suffixField;
    
    private user userChangedByField;
    
    private user userCreatedByField;
    
    private user userVoidedByField;
    
    private string villageField;
    
    private string villageIdField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string account {
        get {
            return this.accountField;
        }
        set {
            this.accountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public identifierDomain accountIdentifierDomain {
        get {
            return this.accountIdentifierDomainField;
        }
        set {
            this.accountIdentifierDomainField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string address1 {
        get {
            return this.address1Field;
        }
        set {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public addressType addressType {
        get {
            return this.addressTypeField;
        }
        set {
            this.addressTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int birthOrder {
        get {
            return this.birthOrderField;
        }
        set {
            this.birthOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool birthOrderSpecified {
        get {
            return this.birthOrderFieldSpecified;
        }
        set {
            this.birthOrderFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string birthPlace {
        get {
            return this.birthPlaceField;
        }
        set {
            this.birthPlaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cell {
        get {
            return this.cellField;
        }
        set {
            this.cellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string cellId {
        get {
            return this.cellIdField;
        }
        set {
            this.cellIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string countryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom1 {
        get {
            return this.custom1Field;
        }
        set {
            this.custom1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom10 {
        get {
            return this.custom10Field;
        }
        set {
            this.custom10Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom11 {
        get {
            return this.custom11Field;
        }
        set {
            this.custom11Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom12 {
        get {
            return this.custom12Field;
        }
        set {
            this.custom12Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom13 {
        get {
            return this.custom13Field;
        }
        set {
            this.custom13Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom14 {
        get {
            return this.custom14Field;
        }
        set {
            this.custom14Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom15 {
        get {
            return this.custom15Field;
        }
        set {
            this.custom15Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom16 {
        get {
            return this.custom16Field;
        }
        set {
            this.custom16Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom17 {
        get {
            return this.custom17Field;
        }
        set {
            this.custom17Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom18 {
        get {
            return this.custom18Field;
        }
        set {
            this.custom18Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom19 {
        get {
            return this.custom19Field;
        }
        set {
            this.custom19Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom2 {
        get {
            return this.custom2Field;
        }
        set {
            this.custom2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom20 {
        get {
            return this.custom20Field;
        }
        set {
            this.custom20Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom3 {
        get {
            return this.custom3Field;
        }
        set {
            this.custom3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom4 {
        get {
            return this.custom4Field;
        }
        set {
            this.custom4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom5 {
        get {
            return this.custom5Field;
        }
        set {
            this.custom5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom6 {
        get {
            return this.custom6Field;
        }
        set {
            this.custom6Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom7 {
        get {
            return this.custom7Field;
        }
        set {
            this.custom7Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom8 {
        get {
            return this.custom8Field;
        }
        set {
            this.custom8Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string custom9 {
        get {
            return this.custom9Field;
        }
        set {
            this.custom9Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateChanged {
        get {
            return this.dateChangedField;
        }
        set {
            this.dateChangedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateChangedSpecified {
        get {
            return this.dateChangedFieldSpecified;
        }
        set {
            this.dateChangedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateCreatedSpecified {
        get {
            return this.dateCreatedFieldSpecified;
        }
        set {
            this.dateCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateOfBirth {
        get {
            return this.dateOfBirthField;
        }
        set {
            this.dateOfBirthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateOfBirthSpecified {
        get {
            return this.dateOfBirthFieldSpecified;
        }
        set {
            this.dateOfBirthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateVoided {
        get {
            return this.dateVoidedField;
        }
        set {
            this.dateVoidedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateVoidedSpecified {
        get {
            return this.dateVoidedFieldSpecified;
        }
        set {
            this.dateVoidedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string deathInd {
        get {
            return this.deathIndField;
        }
        set {
            this.deathIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime deathTime {
        get {
            return this.deathTimeField;
        }
        set {
            this.deathTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool deathTimeSpecified {
        get {
            return this.deathTimeFieldSpecified;
        }
        set {
            this.deathTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string degree {
        get {
            return this.degreeField;
        }
        set {
            this.degreeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string district {
        get {
            return this.districtField;
        }
        set {
            this.districtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string districtId {
        get {
            return this.districtIdField;
        }
        set {
            this.districtIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ethnicGroup ethnicGroup {
        get {
            return this.ethnicGroupField;
        }
        set {
            this.ethnicGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string familyName {
        get {
            return this.familyNameField;
        }
        set {
            this.familyNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string familyName2 {
        get {
            return this.familyName2Field;
        }
        set {
            this.familyName2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string fatherName {
        get {
            return this.fatherNameField;
        }
        set {
            this.fatherNameField = value;
        }
    }
    
    /// <remarks/>
    public gender gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string givenName {
        get {
            return this.givenNameField;
        }
        set {
            this.givenNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string groupNumber {
        get {
            return this.groupNumberField;
        }
        set {
            this.groupNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public language language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string maritalStatusCode {
        get {
            return this.maritalStatusCodeField;
        }
        set {
            this.maritalStatusCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string middleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string motherName {
        get {
            return this.motherNameField;
        }
        set {
            this.motherNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string mothersMaidenName {
        get {
            return this.mothersMaidenNameField;
        }
        set {
            this.mothersMaidenNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string multipleBirthInd {
        get {
            return this.multipleBirthIndField;
        }
        set {
            this.multipleBirthIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public nameType nameType {
        get {
            return this.nameTypeField;
        }
        set {
            this.nameTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public nationality nationality {
        get {
            return this.nationalityField;
        }
        set {
            this.nationalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int personId {
        get {
            return this.personIdField;
        }
        set {
            this.personIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool personIdSpecified {
        get {
            return this.personIdFieldSpecified;
        }
        set {
            this.personIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("personIdentifiers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public personIdentifier[] personIdentifiers {
        get {
            return this.personIdentifiersField;
        }
        set {
            this.personIdentifiersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneAreaCode {
        get {
            return this.phoneAreaCodeField;
        }
        set {
            this.phoneAreaCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneCountryCode {
        get {
            return this.phoneCountryCodeField;
        }
        set {
            this.phoneCountryCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneExt {
        get {
            return this.phoneExtField;
        }
        set {
            this.phoneExtField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string phoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public phoneType phoneType {
        get {
            return this.phoneTypeField;
        }
        set {
            this.phoneTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string postalCode {
        get {
            return this.postalCodeField;
        }
        set {
            this.postalCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string prefix {
        get {
            return this.prefixField;
        }
        set {
            this.prefixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string province {
        get {
            return this.provinceField;
        }
        set {
            this.provinceField = value;
        }
    }
    
    /// <remarks/>
    public race race {
        get {
            return this.raceField;
        }
        set {
            this.raceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public religion religion {
        get {
            return this.religionField;
        }
        set {
            this.religionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sector {
        get {
            return this.sectorField;
        }
        set {
            this.sectorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string sectorId {
        get {
            return this.sectorIdField;
        }
        set {
            this.sectorIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ssn {
        get {
            return this.ssnField;
        }
        set {
            this.ssnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user userChangedBy {
        get {
            return this.userChangedByField;
        }
        set {
            this.userChangedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user userCreatedBy {
        get {
            return this.userCreatedByField;
        }
        set {
            this.userCreatedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user userVoidedBy {
        get {
            return this.userVoidedByField;
        }
        set {
            this.userVoidedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string village {
        get {
            return this.villageField;
        }
        set {
            this.villageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string villageId {
        get {
            return this.villageIdField;
        }
        set {
            this.villageIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class race : baseObject {
    
    private int raceCdField;
    
    private bool raceCdFieldSpecified;
    
    private string raceCodeField;
    
    private string raceDescriptionField;
    
    private string raceNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int raceCd {
        get {
            return this.raceCdField;
        }
        set {
            this.raceCdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool raceCdSpecified {
        get {
            return this.raceCdFieldSpecified;
        }
        set {
            this.raceCdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string raceCode {
        get {
            return this.raceCodeField;
        }
        set {
            this.raceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string raceDescription {
        get {
            return this.raceDescriptionField;
        }
        set {
            this.raceDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string raceName {
        get {
            return this.raceNameField;
        }
        set {
            this.raceNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class personLink : baseObject {
    
    private int clusterIdField;
    
    private bool clusterIdFieldSpecified;
    
    private System.DateTime dateCreatedField;
    
    private bool dateCreatedFieldSpecified;
    
    private linkSource linkSourceField;
    
    private person personLeftField;
    
    private int personLinkIdField;
    
    private bool personLinkIdFieldSpecified;
    
    private person personRightField;
    
    private user userCreatedByField;
    
    private double weightField;
    
    private bool weightFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int clusterId {
        get {
            return this.clusterIdField;
        }
        set {
            this.clusterIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool clusterIdSpecified {
        get {
            return this.clusterIdFieldSpecified;
        }
        set {
            this.clusterIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateCreatedSpecified {
        get {
            return this.dateCreatedFieldSpecified;
        }
        set {
            this.dateCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public linkSource linkSource {
        get {
            return this.linkSourceField;
        }
        set {
            this.linkSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public person personLeft {
        get {
            return this.personLeftField;
        }
        set {
            this.personLeftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int personLinkId {
        get {
            return this.personLinkIdField;
        }
        set {
            this.personLinkIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool personLinkIdSpecified {
        get {
            return this.personLinkIdFieldSpecified;
        }
        set {
            this.personLinkIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public person personRight {
        get {
            return this.personRightField;
        }
        set {
            this.personRightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user userCreatedBy {
        get {
            return this.userCreatedByField;
        }
        set {
            this.userCreatedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool weightSpecified {
        get {
            return this.weightFieldSpecified;
        }
        set {
            this.weightFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class personPagedRequest {
    
    private int firstResultField;
    
    private int maxResultsField;
    
    private person personField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int firstResult {
        get {
            return this.firstResultField;
        }
        set {
            this.firstResultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int maxResults {
        get {
            return this.maxResultsField;
        }
        set {
            this.maxResultsField = value;
        }
    }
    
    /// <remarks/>
    public person person {
        get {
            return this.personField;
        }
        set {
            this.personField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class reviewRecordPair : baseObject {
    
    private System.DateTime dateCreatedField;
    
    private bool dateCreatedFieldSpecified;
    
    private System.DateTime dateReviewedField;
    
    private bool dateReviewedFieldSpecified;
    
    private linkSource linkSourceField;
    
    private person personLeftField;
    
    private person personRightField;
    
    private bool recordsMatchField;
    
    private bool recordsMatchFieldSpecified;
    
    private int reviewRecordPairIdField;
    
    private bool reviewRecordPairIdFieldSpecified;
    
    private user userCreatedByField;
    
    private user userReviewedByField;
    
    private double weightField;
    
    private bool weightFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateCreated {
        get {
            return this.dateCreatedField;
        }
        set {
            this.dateCreatedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateCreatedSpecified {
        get {
            return this.dateCreatedFieldSpecified;
        }
        set {
            this.dateCreatedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime dateReviewed {
        get {
            return this.dateReviewedField;
        }
        set {
            this.dateReviewedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dateReviewedSpecified {
        get {
            return this.dateReviewedFieldSpecified;
        }
        set {
            this.dateReviewedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public linkSource linkSource {
        get {
            return this.linkSourceField;
        }
        set {
            this.linkSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public person personLeft {
        get {
            return this.personLeftField;
        }
        set {
            this.personLeftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public person personRight {
        get {
            return this.personRightField;
        }
        set {
            this.personRightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool recordsMatch {
        get {
            return this.recordsMatchField;
        }
        set {
            this.recordsMatchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool recordsMatchSpecified {
        get {
            return this.recordsMatchFieldSpecified;
        }
        set {
            this.recordsMatchFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int reviewRecordPairId {
        get {
            return this.reviewRecordPairIdField;
        }
        set {
            this.reviewRecordPairIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool reviewRecordPairIdSpecified {
        get {
            return this.reviewRecordPairIdFieldSpecified;
        }
        set {
            this.reviewRecordPairIdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user userCreatedBy {
        get {
            return this.userCreatedByField;
        }
        set {
            this.userCreatedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public user userReviewedBy {
        get {
            return this.userReviewedByField;
        }
        set {
            this.userReviewedByField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public double weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool weightSpecified {
        get {
            return this.weightFieldSpecified;
        }
        set {
            this.weightFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class stringList {
    
    private string[] dataField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string[] data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
}
